import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=fileURLToPath(new URL('../',import.meta.url)).replace(/\/$/,'');
const out=process.argv[2] || root+'/generated';
const read=async n=>(await fs.readFile(root+'/data/'+n+'.jsonl','utf8')).trim().split('\n').map(JSON.parse);
const [sources,reviews,routes,examples,performance,targets,queries,checks,plan]=await Promise.all(['expansion_candidates','priority_reviews','observed_routes','commercial_examples','source_performance','research_targets','buyer_language_queries','page_checks','initial_plan'].map(read));
const registry=await read('source_registry');const sourceMap=new Map(registry.map(x=>[x.source_id,x]));
const wb=Workbook.create(),navy='#183B51',ink='#213C4B',muted='#637583',amber='#FFF1CF';
const names=['Обзор','Новые 417','Проверки 100','Приглашения и запросы','Маршруты','Направления','Пилот 20','Эффективность','Поиск 360','Журнал чтения','Бюджет','Claude'];names.forEach(n=>wb.worksheets.add(n));
const col=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
const labels={not_established:'Не установлено',not_checked:'Не проверен',content_read_partial:'Прочитана часть',preview_only:'Только карточка',fetch_failed:'Ошибка доступа',empty_extraction:'Пустое извлечение',audience_or_organization_seen:'Аудитория / организация',topic_or_audience_candidate:'Кандидат по теме / аудитории',explicit_application_or_contact:'Есть форма / контакт',new_source_key:'Новый ключ источника',discovery_context_only:'Только контекст поиска',unknown:'Не установлена',template_not_executed:'Шаблон — не запускался'};
const tr=x=>labels[x]??x??'';
function table(name,title,note,heads,rows,widths,id){
 const s=wb.worksheets.getItem(name),end=col(heads.length),last=rows.length+5;s.showGridLines=false;
 s.getRange(`A1:${end}${last}`).format={font:{name:'Arial',size:10,color:ink},verticalAlignment:'top'};
 widths.forEach((w,i)=>s.getRange(`${col(i+1)}1:${col(i+1)}${last}`).format.columnWidthPx=w);
 s.getRange('A2').values=[[title]];s.getRange('A2').format={font:{size:17,bold:true,color:navy},rowHeightPx:35};
 s.getRange('A3').values=[[note]];s.getRange('A3').format={font:{color:muted},rowHeightPx:30};
 s.getRange(`A5:${end}5`).values=[heads];s.getRange(`A6:${end}${last}`).values=rows.map(r=>r.map(v=>typeof v==='string'&&v.startsWith('=')?"'"+v:v));
 s.tables.add(`A5:${end}${last}`,true,id).style='TableStyleMedium2';
 s.getRange(`A5:${end}5`).format={fill:navy,font:{bold:true,color:'#FFFFFF'},wrapText:true,rowHeightPx:48};s.getRange(`A6:${end}${last}`).format.wrapText=true;
 rows.forEach((r,i)=>{const lines=Math.max(...r.map((v,j)=>String(v??'').split('\n').reduce((a,t)=>a+Math.max(1,Math.ceil(t.length/Math.max(10,(widths[j]-14)/7))),0)));s.getRange(`A${i+6}:${end}${i+6}`).format.rowHeightPx=Math.max(44,lines*16+15);});
 s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(2);return s;
}
sources.sort((a,b)=>Boolean(b.review_id)-Boolean(a.review_id)||a.research_track.localeCompare(b.research_track));
table('Новые 417','417 новых кандидатов • 10 направлений','Новый ключ домена/социального адреса не равен новой независимой организации. Полные свидетельства — JSONL.',
['Источник ID','Название / заголовок','Направление поиска','Вывод / следующий фокус','Страна — подсказка','Платформа','Тип источника','Доступ','Присутствие покупателя','Профиль МИСБ','Свежесть','Возможность действия','Новый охват','Надежность сбора','Проверка ID','URL','Происхождение'],sources.map(s=>[s.source_id,s.name,s.research_track_label,s.note,tr(s.country_hint),s.platform,s.source_kind,tr(s.access_state),tr(s.buyer_presence),tr(s.misb_relevance),tr(s.freshness),tr(s.actionability),tr(s.incremental_coverage),tr(s.collection_reliability),s.review_id,s.url,s.discovery_refs.join('; ')]),[150,340,240,560,155,130,240,200,230,240,190,240,190,220,150,510,300],'NewSources');
table('Проверки 100','100 приоритетных источников • 135 попыток чтения','Наблюдения и ограничения; полный 14-дневный охват не установлен. Контакты публичные, владелец заказа не подтвержден.',
['Проверка ID','Источник','Результат чтения','Содержательный вывод','Тип','Дата в источнике','Тип даты','Публичный контакт','Следующий шаг','Попыток','URL','Источник ID','Свидетельства'],reviews.map(r=>[r.review_id,r.name,tr(r.access_state),r.note,r.source_kind,r.observed_date,r.date_kind,r.public_contact,r.next_action,r.page_attempts,r.url,r.source_id,r.web_refs.join('; ')]),[150,310,215,650,260,180,220,330,450,100,500,150,340],'Reviews');
table('Приглашения и запросы','21 пример для адресной проверки','Приглашения и исторические запросы. Ни один пример не подтвержден как новый открытый покупательский заказ.',
['Пример ID','Источник','Тип примера','Что найдено','Дата в источнике','Тип даты','Свежесть 14 дней','Открыто сейчас','Маршрут контакта','Следующий шаг','URL','Источник ID'],examples.map(e=>[e.example_id,sourceMap.get(e.source_id)?.name,e.kind,e.summary,e.observed_date,e.date_kind,'Не подтверждена','Не подтверждено',e.public_contact,e.next_action,e.url,e.source_id]),[140,310,245,650,185,240,175,185,330,450,500,150],'Examples');
table('Маршруты','20 наблюденных переходов','Точный адрес получен из ссылки; содержимое чатов, форм или вложений могло остаться недоступно.',
['Маршрут ID','Источник','Ссылка / назначение','Доступ','Точный URL','Связь','Родительский URL','Источник ID'],routes.map(r=>[r.route_id,sourceMap.get(r.source_id)?.name,r.label,tr(r.read_state),r.url,r.relationship,r.parent_url,r.source_id]),[160,310,380,220,520,230,510,150],'Routes');
table('Направления','Разнообразие источников и оставшиеся пробелы','Направление — исследовательская корзина. Количество не подтверждает тип каждой организации.',
['Направление','Исходная цель','Найдено кандидатов','Недобор к цели','Что проверять дальше'],targets.map(t=>[t.label,t.initial_target,t.candidates_discovered,t.gap,t.gap?'Добрать направление; проверить роль организации, покупателей и точные социальные маршруты.':'Углубить комментарии, вложения, авторов и первоисточники; не прекращать разведку.']),[330,155,195,190,650],'Tracks');
table('Пилот 20','Стартовый план • 20 источников','16 проверенных + 4 разведочных. План не запускался; разные направления, доступность HTTP еще не установлена.',
['Источник ID','Название','Направление','Поток','Ручной доступ','URL','Статус'],plan.map(p=>[p.source_id,p.name,p.research_track,p.lane==='exploration'?'Разведка':'Приоритет',p.manual_only?'Да':'Проверить HTTP',p.entry_url,'Запланирован — не запущен']),[160,350,230,170,220,520,260],'Pilot');
const perf=table('Эффективность','439 источников • будущие результаты пилота','Желтые поля — ручной ввод. Пусто означает неизвестно. Формулы считают стоимость только при известных данных.',
['Источник ID','Название','Направление','Наблюдений','Уникальных возможностей','Квалифицированных','Покупатель подтвердил','Заказов','Расход, ₽','Время, мин','₽ / квалифицированную','Мин / квалифицированную','Начало периода','Конец периода','Следующий шаг'],performance.map(p=>[p.source_id,p.name,p.research_track,null,null,null,null,null,null,null,null,null,null,null,null]),[160,350,230,155,190,180,190,120,140,145,205,205,160,160,430],'Performance');
perf.getRange(`D6:J${performance.length+5}`).format.fill=amber;perf.getRange(`M6:O${performance.length+5}`).format.fill=amber;
for(let r=6;r<=performance.length+5;r++){
 perf.getRange(`K${r}`).formulas=[[`=IF(AND(ISNUMBER(I${r}),ISNUMBER(F${r}),F${r}>0),I${r}/F${r},"")`]];
 perf.getRange(`L${r}`).formulas=[[`=IF(AND(ISNUMBER(J${r}),ISNUMBER(F${r}),F${r}>0),J${r}/F${r},"")`]];
}perf.getRange(`I6:L${performance.length+5}`).setNumberFormat('#,##0.0');
table('Поиск 360','360 шаблонов на языке заказчика','Шаблоны не запускались. 120 действительно выполненных запросов отдельно сохранены в executed_searches.jsonl.',
['Запрос ID','Страна','Роль','Запрос','Статус'],queries.map(q=>[q.query_id,q.country,q.role,q.query,tr(q.status)]),[150,155,230,680,280],'Queries');
table('Журнал чтения','135 попыток • ссылки и хеши свидетельств','Чтение публичных страниц; ошибки и повторы сохранены. Полные тексты сторонних страниц в пакет не включены.',
['Попытка ID','Источник','Цель чтения','Результат','Дата проверки','URL','Web-ref','SHA-256 ответа'],checks.map(c=>[c.attempt_id,sourceMap.get(c.source_id)?.name,c.purpose,tr(c.read_state),c.checked_on,c.url,c.web_refs.join('; '),c.response_sha256]),[150,330,215,220,150,530,320,550],'Reading');
const b=wb.worksheets.getItem('Бюджет');b.showGridLines=false;b.getRange('A1:D23').format={font:{name:'Arial',size:11,color:ink},verticalAlignment:'center'};[400,180,180,350].forEach((w,i)=>b.getRange(`${col(i+1)}1:${col(i+1)}23`).format.columnWidthPx=w);
b.getRange('A2').values=[['Общий предел • 10 000 ₽ / месяц']];b.getRange('A2').format={font:{size:18,bold:true,color:navy},rowHeightPx:38};b.getRange('A3').values=[['Плановые потолки, не проверенные тарифы. Платные вызовы не запускались.']];
b.getRange('A5:B5').values=[['Месячный предел, ₽',10000]];b.getRange('A7:D7').values=[['Статья','План, ₽','Факт, ₽','Факт известен']];b.getRange('A7:D7').format={fill:navy,font:{bold:true,color:'#FFFFFF'}};
b.getRange('A8:D13').values=[['Хостинг и хранение',1000,null,null],['Поиск и данные',2500,null,null],['LLM',3000,null,null],['OCR / аудио',500,null,null],['Доступ / API',1000,null,null],['Резерв',2000,null,null]];b.getRange('B8:C13').format.fill=amber;
for(let r=8;r<=13;r++)b.getRange(`D${r}`).formulas=[[`=IF(ISNUMBER(C${r}),"Да","Неизвестен")`]];
b.getRange('A15:A21').values=[['Распределено, ₽'],['Остаток плана, ₽'],['Полный факт, ₽'],['Остаток после факта, ₽'],['Состояние лимита'],['Разведка — доля мощности'],['Труд — учитывать отдельно']];
b.getRange('B15').formulas=[['=SUM(B8:B13)']];b.getRange('B16').formulas=[['=B5-B15']];b.getRange('B17').formulas=[['=IF(COUNT(C8:C13)=6,SUM(C8:C13),"Неизвестен")']];b.getRange('B18').formulas=[['=IF(ISNUMBER(B17),B5-B17,"Неизвестен")']];b.getRange('B19').formulas=[['=IF(ISNUMBER(B18),IF(B18>=0,"В пределах лимита","Превышение"),"Внести факт")']];b.getRange('B20').values=[[.2]];b.getRange('B20').setNumberFormat('0%');b.getRange('A23').values=[['Если 10 000 ₽ включает труд, сократить объем пилота в пределах общего бюджета.']];b.getRange('A5:D23').format.rowHeightPx=34;
const guide=[['Начать','START_HERE_CLAUDE_V7.txt и SOURCE_OPERATING_GUIDE.txt в ZIP.'],['Все прошлые материалы','v6/ сохранен полностью, включая v5, HR-сайты, Telegram, социальные сети и КУ.'],['417 кандидатов','Новые ключи адресов; организация, покупательский поток и работоспособность сбора не всегда проверены.'],['100 проверок','89 — прочитана часть; 2 — карточка; 6 — ошибки; 3 — пустое извлечение.'],['21 пример','Приглашения и исторические запросы; не список 21 свежего заказа.'],['Шесть осей','Покупатели, профиль МИСБ, свежесть, действие, новый охват, надежность сбора.'],['Без удаления','Дубли связывать; слабые, заблокированные и архивные источники сохранять.'],['Выполненные поиски','120 запросов — executed_searches.jsonl; 360 шаблонов — еще не выполнялись.'],['Проверить пакет','python code/source_ops.py validate'],['Подготовить план','python code/source_ops.py plan --limit 20 --out plan.jsonl'],['Запуск','Команды — в руководстве. Реальный пилот, расписание, оплаты и рассылки не запускались.'],['Обратная связь','Желтые поля книги — ввод; перенос в JSONL по source_id явный, автоматической синхронизации нет.'],['Результат 10x','Цель, а не измеренный эффект. Нужны базовая линия и одинаковые условия сравнения.']];
table('Claude','Инструкция передачи и границы результата','Точные URL и машинные данные находятся в полном ZIP. Эта книга дополняет прежние рабочие книги.', ['Раздел','Инструкция'],guide,[300,1050],'ClaudeGuide');
const v=wb.worksheets.getItem('Обзор');v.showGridLines=false;v.getRange('A1:D26').format={font:{name:'Arial',size:11,color:ink},verticalAlignment:'center'};[425,175,40,700].forEach((w,i)=>v.getRange(`${col(i+1)}1:${col(i+1)}26`).format.columnWidthPx=w);
v.getRange('A2').values=[['МИСБ • расширение источников v7']];v.getRange('A2').format={font:{size:20,bold:true,color:navy},rowHeightPx:42};v.getRange('A3').values=[['Срез 02.10.2026 • все прежние материалы сохранены в полном ZIP']];
const stats=[['Новых кандидатов',"=COUNTA('Новые 417'!A6:A422)"],['Приоритетных источников проверено',"=COUNTA('Проверки 100'!A6:A105)"],['Попыток чтения',"=COUNTA('Журнал чтения'!A6:A140)"],['Точных наблюденных переходов',"=COUNTA('Маршруты'!A6:A25)"],['Примеров приглашений / запросов',"=COUNTA('Приглашения и запросы'!A6:A26)"],['Выполненных поисковых запросов',120],['Всего ключей в новом поиске',1026],['Сохранено прежних маршрутов',4156],['Новых подтвержденных покупателей',0],['Полный охват 14 дней','Не установлен'],['10x прирост качественных лидов','Не измерен']];
stats.forEach(([k,value],i)=>{let r=i+6;v.getRange(`A${r}`).values=[[k]];if(typeof value==='string'&&value.startsWith('='))v.getRange(`B${r}`).formulas=[[value]];else v.getRange(`B${r}`).values=[[value]];});v.getRange('A6:B16').format.rowHeightPx=35;
v.getRange('D6:D13').values=[['Как превратить расширение в поток возможностей'],['Проверки 100 → точный запрос / приглашение → актуальность → владелец → соответствие МИСБ.'],['417 кандидатов распределены по 10 направлениям. Это новые адреса, а не 417 подтвержденных покупателей.'],['В расширении преобладают сайты: 392 из 417. Социальные маршруты и закрытые чаты требуют дальнейшего углубления.'],['2634 задачи по поверхностям сохраняют комментарии, вложения, авторов, первоисточники и партнерство в зоне поиска.'],['439 карточек эффективности: новые источники и проверенные прежние. Вводить фактические результаты пилота.'],['Разведка получает 20% мощности; слабые и редкие источники не удаляются.'],['Граница свежести: 19.09–02.10.2026. Не путать дату чтения, публикации, события и дедлайн.']];v.getRange('D6:D13').format={wrapText:true,rowHeightPx:61};v.getRange('D6').format.font.bold=true;
v.getRange('A19').values=[['Следующий шаг: ограниченный пилот 20 источников и ручная проверка пропусков.']];v.getRange('A21').values=[['Пилот и расписание не запущены; весь v6 находится внутри ZIP.']];v.getRange('A23').values=[['Книга дополняет полный архив. Машинные данные и код — в пакете для Claude.']];v.getRange('A25').values=[['10 000 ₽ / месяц — общий технический денежный предел; тарифы и факт требуют учета.']];v.getRange('A19:A25').format.rowHeightPx=32;
wb.recalculate();if(Number(v.getRange('B6').values[0][0])!==417||Number(v.getRange('B7').values[0][0])!==100)throw Error('Summary count');
if(b.getRange('B17').values[0][0]!=='Неизвестен')throw Error('Unknown spending');
b.getRange('C8:C13').values=[[0],[0],[0],[0],[0],[0]];wb.recalculate();if(Number(b.getRange('B18').values[0][0])!==10000)throw Error('Zero spending');b.getRange('C8').values=[[11000]];wb.recalculate();if(b.getRange('B19').values[0][0]!=='Превышение')throw Error('Budget guard');b.getRange('C8:C13').values=[[null],[null],[null],[null],[null],[null]];
perf.getRange('F6').values=[[2]];perf.getRange('I6').values=[[0]];wb.recalculate();if(Number(perf.getRange('K6').values[0][0])!==0)throw Error('Zero cost');perf.getRange('F6').values=[[0]];wb.recalculate();if(perf.getRange('K6').values[0][0]!=='')throw Error('Zero denominator');perf.getRange('F6').values=[[null]];perf.getRange('I6').values=[[null]];wb.recalculate();
const err=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:20},maxChars:1600});console.log(err.ndjson);
await fs.mkdir(out,{recursive:true});for(let i=0;i<names.length;i++){let n=names[i],range=n==='Обзор'?'A1:D25':n==='Бюджет'?'A1:D23':n==='Claude'?'A1:B10':n==='Направления'?'A1:E15':'A1:D8';const pic=await wb.render({sheetName:n,range,scale:1,format:'png'});await fs.writeFile(`${out}/preview-${i}.png`,new Uint8Array(await pic.arrayBuffer()));}
const pic=await wb.render({sheetName:'Эффективность',range:'F5:L8',scale:1,format:'png'});await fs.writeFile(`${out}/formula-preview.png`,new Uint8Array(await pic.arrayBuffer()));
await(await SpreadsheetFile.exportXlsx(wb)).save(out+'/MISB_Sources_v7_2026-10-02.xlsx');
await fs.writeFile(root+'/audit/workbook_checks.json',JSON.stringify({sheets:names.length,rendered_sheets:names,summary_formulas_passed:true,budget_unknown_zero_overrun_passed:true,unit_cost_zero_and_denominator_passed:true,formula_error_inspection:err.ndjson},null,2));console.log('Workbook exported');
